services:
  nginx:
    image: nginx:latest
    container_name: smart-note-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - smartnote-ui
      - smartnote-api
    restart: always

  smartnote-ui:
    build:
      context: ./smartnote-ui
      dockerfile: Dockerfile
    image: local-smart-note-ui
    container_name: smart-note-ui
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - smartnote-api

  smartnote-api:
    build:
      context: ./smartnote-api
      dockerfile: Dockerfile
    image: local-smart-note-api
    container_name: smart-note-api
    ports:
      - "8082:8081"
    environment:
      - MONGO_URI=
      - HUGGINGFACE_API_KEY=
      - JWT_SECRET=
    restart: always
